const express = require("express");
const router = express.Router();
const authController = require("../controllers/authController");
router.post("/login", authController.handleLogin);
router.post("/createAnnouncement", authController.handleNewAnnouncement);
router.post("/createReview", authController.createReview);
router.post("/createEvent", authController.handleNewEvent);
router.post("/createAchievement", authController.handleNewAchievement);
router.post("/createStudent", authController.handleNewStudent);
router.get("/getUser/:email", authController.getUserByEmail);
router.get("/getUsers/:position", authController.getUsersByPosition);
router.get("/getUsers/:grade", authController.getUserByGrade);
router.get("/getUsers", authController.getUsers);
router.get("/getStudents", authController.getStudents);
router.get("/getAnnouncements", authController.getAnnouncements);
router.get("/getAchievements", authController.getAchievements);
router.get("/getEvents", authController.getEvents);
router.get("/getReviews", authController.getReviews);
router.delete("/deleteEvent", authController.deleteEvent);
router.delete("/deleteAchievement", authController.deleteAchievement);
router.delete("/deleteAnnouncement", authController.deleteAnnouncement);
router.delete("/deleteReview/:id", authController.deleteReview);
router.delete("/deleteStudent/:id", authController.deleteStudent);

module.exports = router;
