const express = require("express");
const router = express.Router();
const authController = require("../controllers/authController");
router.post("/login", authController.handleLogin);
router.post("/createHospital", authController.handleNewHospital);
router.post("/createReview", authController.createReview);
router.post("/createDisease", authController.handleNewDisease);
router.post("/createHealthTip", authController.handleNewHealthTip);
router.post("/bookDoctor", authController.bookDoctor);
router.get("/getDoctor/:email", authController.getDoctorByEmail);
router.get("/getDoctors/:specialization", authController.getDoctorByRole);
router.get("/getDisease", authController.getDisease);
router.get("/getHospitals", authController.getHospitals);
router.get("/getReviews", authController.getReviews);
router.get("/getPatients", authController.getPatients);
router.get("/getPatients/:doctorname", authController.getPatientsByDoctorName);
router.put("/updateHospital", authController.updateHospital);
router.put("/updateDisease", authController.updateDisease);
router.delete("/deleteHospital", authController.deleteHospital);
router.delete("/deleteDisease", authController.deleteDisease);
router.delete("/deleteHealthTip", authController.deleteHealthTip);

module.exports = router;
